# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print("NumPy version:", np.__version__)

NumPy version: 1.22.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

7

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
vector = np.arange(10,50)
reverse_vector = vector [::-1]
reverse_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
matrix= np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
my_list = [1,2,0,0,4,0]
my_array = np.array(my_list)
non_zero_elements = np.nonzero(my_array)
non_zero_elements

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [24]:
random_array = np.random.rand(3,3,3)
random_array

array([[[0.69126246, 0.10406221, 0.85248852],
        [0.24357708, 0.67061412, 0.16956799],
        [0.14039469, 0.65355338, 0.50964574]],

       [[0.11903096, 0.30366074, 0.1452164 ],
        [0.25752275, 0.72725951, 0.77187346],
        [0.1771088 , 0.57233285, 0.57084057]],

       [[0.8020922 , 0.44537318, 0.72995016],
        [0.87527661, 0.96283996, 0.76057624],
        [0.50778897, 0.39301684, 0.36200717]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
random_array = np.random.rand(10,10)
random_array_min = np.min(random_array)
random_array_max = np.max(random_array)
print("Min Value",random_array_min)
print("Max Value",random_array_max)

Min Value 0.0052525697485276135
Max Value 0.9955301995959026


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [33]:
random_array = np.random.rand(30)
random_array_mean = np.mean(random_array)
random_array_mean

0.5229358885114432

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
array = np.pad(np.zeros((3, 3)), pad_width=1, mode='constant', constant_values=1)
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [39]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
border_array  = np.pad(array, pad_width=1, mode='constant', constant_values=0)
border_array

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
diagonal_values = [1, 2, 3, 4]
diagonal_matrix = np.diag(diagonal_values, k=-1)
diagonal_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [52]:
checkerboard = np.zeros((8 ,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
shape = (6,7,8)
x, y, z = np.unravel_index(100, shape)
print("100th Element are: ",(x,y,z))

100th Element are:  (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [51]:
checkerboard_pattern = np.array([[1,0],[0,1]])
checkerboard_pattern_tile = np.tile(checkerboard_pattern,(4,4))
checkerboard_pattern_tile

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [54]:
matrix = np.random.rand(5,5)
mean = np.mean(matrix)
std = np.std(matrix)
normalized = (matrix - mean) / std
normalized

array([[-1.32229822,  0.63364232,  0.86709782, -0.16616655, -0.25397992],
       [ 1.28712805,  0.68232285, -0.96714887,  1.57711211,  0.06927066],
       [-0.83515292,  1.64443873,  1.33812763,  0.09349576, -1.70693244],
       [-0.56843105,  1.36165025,  0.51951183, -0.97991421, -1.24326266],
       [ 0.10795603,  0.0243863 , -1.71013215, -0.64433935,  0.19161802]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [56]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color_data = (255, 128, 0, 255)
color_array = np.array(color_data, dtype=color_dtype)
color_array

array((255, 128, 0, 255),
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [58]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.matmul(matrix1, matrix2)
result

array([[0.46580077, 0.91442546],
       [0.57311901, 0.56939457],
       [0.67231255, 0.71622016],
       [0.5953526 , 0.73225633],
       [0.26233323, 0.39365872]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [59]:
arr = np.array([1, 5, 7, 2, 4, 6, 9, 8, 3])
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 1, -5, -7,  2, -4, -6,  9, -8, -3])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [60]:
print(sum(range(5),-1)) # simple sum python
from numpy import *
print(sum(range(5),-1)) # numpy sum

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [61]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-61-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-61-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [62]:
float_array = np.array([2.3, -1.5, 3.7, -4.2, 5.8])
rounded_array = np.ceil(float_array)
rounded_array

array([ 3., -1.,  4., -4.,  6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [63]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
common_values

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [68]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [70]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print("Today Date is: ",today)
print("Yesterday Date is: ",yesterday)
print("Tomorrow Date is: ",tomorrow)

Today Date is:  2023-07-24
Yesterday Date is:  2023-07-23
Tomorrow Date is:  2023-07-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [71]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')
dates_of_july_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')
dates_of_july_2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [76]:
A = np.array([1, 2, 3, 4, 5],dtype=float)
B = np.array([10, 20, 30, 40, 50])
A = np.add(A, B)
A = np.multiply(A, -A / 2)
A

array([  -60.5,  -242. ,  -544.5,  -968. , -1512.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [77]:
random_array = np.random.rand(5) * 100
integer_part = np.floor(random_array)
integer_part

array([96., 55., 75., 97., 85.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [84]:
matrix = np.arange(5).reshape(5, 1) + np.arange(5)
matrix

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [91]:
def integer_generator():
    for i in range(10):
        yield i
result_array = np.fromiter(integer_generator(), dtype=int)
result_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [88]:
vector = np.linspace(0, 1, num=10, endpoint=False)[1:]
vector

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [86]:
array = np.random.rand(10)
sortarray = np.sort(array)
sortarray

array([0.02401474, 0.05792546, 0.24008342, 0.25466637, 0.32845353,
       0.45334561, 0.47144961, 0.66198255, 0.88230199, 0.88593582])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [95]:
small_array = np.array([1, 2, 3, 4, 5])
sum = np.sum(small_array)
sum

15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [105]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)
array_equal = np.array_equal(array1,array2)
array_equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [106]:
my_array = np.array([1, 2, 3, 4, 5])
my_array.flags.writeable = False
my_array

array([1, 2, 3, 4, 5])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [107]:
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
random_vector

array([0.45835011, 0.        , 0.17307068, 0.57807749, 0.58858814,
       0.6050122 , 0.47123551, 0.83946855, 0.67040006, 0.89180666])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [114]:
num_points = 5
x = np.linspace(0, 1, num_points)
y = np.linspace(0, 1, num_points)
X, Y = np.meshgrid(x, y)
coordinates = np.column_stack((X.ravel(), Y.ravel()))
coordinates

array([[0.  , 0.  ],
       [0.25, 0.  ],
       [0.5 , 0.  ],
       [0.75, 0.  ],
       [1.  , 0.  ],
       [0.  , 0.25],
       [0.25, 0.25],
       [0.5 , 0.25],
       [0.75, 0.25],
       [1.  , 0.25],
       [0.  , 0.5 ],
       [0.25, 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.5 ],
       [1.  , 0.5 ],
       [0.  , 0.75],
       [0.25, 0.75],
       [0.5 , 0.75],
       [0.75, 0.75],
       [1.  , 0.75],
       [0.  , 1.  ],
       [0.25, 1.  ],
       [0.5 , 1.  ],
       [0.75, 1.  ],
       [1.  , 1.  ]])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [115]:
X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7])
Cauchy_Matrix = 1.0 / np.subtract.outer(X, Y)
Cauchy_Matrix

array([[-0.25      , -0.2       , -0.16666667],
       [-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [119]:
large_arr = np.arange(100)
np.set_printoptions(threshold=np.inf)
print(large_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [165]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [167]:
array = np.zeros((5, 5), dtype=int)
p = 3
value = 1
rows, cols = array.shape
indices = np.random.choice(rows * cols, p, replace=False)
array1 = np.put(array, indices, value)
print(array1)

None


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [168]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
row_means = np.mean(matrix, axis=1)
matrix_subtracted = matrix - row_means[:, np.newaxis]
print(matrix_subtracted)

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [184]:
array = np.array([[3, 2, 1]])
sorted_indices = array[:,1].argsort()
print(sorted_indices)

[0]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [163]:
array_3d = np.random.rand(5, 5, 3)
array_2d = np.random.rand(5, 5)
result = array_3d * array_2d[:, :, np.newaxis]
result.shape

(5, 5, 3)

#### 72. How to swap two rows of an array? (★★★)

In [162]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row1= 0
row2= 1
arr[[row1, row2]] = arr[[row2, row1]]
print(arr)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [161]:
C = np.array([0, 2, 3, 0, 1])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 2, 2, 4])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [160]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3
window_view = sliding_window_view(arr, window_shape=window_size)
window_cumsum = np.cumsum(window_view, axis=1)
moving_averages = window_cumsum[:, -1] / window_size
print(moving_averages)

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [158]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.array([1, 2, 3, 4, 5])
result = sliding_window_view(Z, window_shape=(3,))
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [155]:
bool_array = np.array([True, False, True, False, True])
bool_array = ~bool_array
bool_array

array([False,  True, False,  True, False])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [154]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = sliding_window_view(Z, window_shape=(4,))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [152]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
rank

2

#### 83. How to find the most frequent value in an array?

In [151]:
arr = np.array([1, 2, 3, 2, 2, 4, 5, 2, 6, 2])
unique_values, counts = np.unique(arr, return_counts=True)
index_of_max_count = np.argmax(counts)
most_frequent_value = unique_values[index_of_max_count]
most_frequent_value

2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [147]:
array_16x16 = np.random.randint(1, 10, size=(16, 16))
block_size = 4
blocks = array_16x16.reshape(4, 4, 4, 4)
block_sum = blocks.sum(axis=(2, 3))
print(block_sum)

[[80 75 70 90]
 [77 90 88 73]
 [79 82 89 86]
 [68 94 96 83]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [145]:
arr = np.array([3, 8, 2, 6, 1, 9, 4, 7, 5])
n = 3
n_largest_values = np.partition(arr, -n)[-n:]
n_largest_values

array([7, 8, 9])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [143]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5])
vector3 = np.array([6, 7, 8])
grid = np.meshgrid(vector1, vector2, vector3)
cartesian_product = np.vstack(grid).T
print(cartesian_product)

[[[1 1 4 5 6 6]
  [2 2 4 5 6 6]
  [3 3 4 5 6 6]]

 [[1 1 4 5 7 7]
  [2 2 4 5 7 7]
  [3 3 4 5 7 7]]

 [[1 1 4 5 8 8]
  [2 2 4 5 8 8]
  [3 3 4 5 8 8]]]


#### 91. How to create a record array from a regular array? (★★★)

In [140]:
regular_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
field_names = ['field1', 'field2', 'field3']
record_array = np.rec.array(regular_array, names=field_names)
print(record_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [135]:
Z = np.random.rand(10)
Z_cubed = np.power(Z, 3)
Z_cubed

array([5.24297682e-01, 1.49064873e-03, 4.71028433e-02, 2.67270120e-01,
       2.43676733e-03, 1.53596835e-03, 1.40747387e-01, 4.47416265e-02,
       7.19153833e-06, 1.64016872e-06])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [2, 3, 1],
              [7, 8, 9],
              [3, 2, 1],
              [9, 8, 7],
              [3, 2, 4],
              [6, 5, 4]])

B = np.array([[1, 2],
              [4, 5]])
rows_contain_elements_of_B = np.all(np.isin(B, A[:, np.newaxis]), axis=2)
selected_rows_A = np.where(np.any(rows_contain_elements_of_B, axis=0))[0]
selected_rows_A_values = A[selected_rows_A]

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [131]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [2, 2, 2],
                   [7, 8, 9],
                   [2, 2, 3],
                   [1, 1, 1],
                   [2, 3, 4],
                   [5, 5, 5],
                   [2, 4, 2],
                   [0, 0, 0]])
_, counts = np.unique(matrix, axis=0, return_counts=True)
unequal_rows = matrix[counts > 1]
print(unequal_rows)

[]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [127]:
vector_ints = np.array([2, 5, 7, 3], dtype=np.uint8)
matrix_binary = np.unpackbits(vector_ints[:, np.newaxis], axis=1)
print(matrix_binary)

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [123]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9],
                     [4, 5, 6]])
unique_rows = np.unique(array_2d, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [122]:
n = 5
X = np.array([[2, 1, 2],
              [3, 0, 2],
              [1, 4, 0],
              [2, 3, 0],
              [0, 0, 5]])
is_multinomial_draw = np.logical_and.reduce(np.mod(X, 1) == 0, axis=1) & (np.sum(X, axis=1) == n)
selected_rows = X[is_multinomial_draw]
selected_rows

array([[2, 1, 2],
       [3, 0, 2],
       [1, 4, 0],
       [2, 3, 0],
       [0, 0, 5]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [121]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
N = 10000
sample_means = [np.mean(np.random.choice(X, size=len(X), replace=True)) for _ in range(N)]
confidence_interval = np.percentile(sample_means, [2.5, 97.5])
print(confidence_interval)

[3.7 7.3]
