**Basic Problems**

In [49]:
#Python Program to Add Two Numbers
num1 = 5
num2 = 7
sum = num1 + num2
print("Sum of", num1 , "and", num2, "is", sum)

Sum of 5 and 7 is 12


In [50]:
#Maximum between two numbers
def maxnumber(a,b):
  if a >= b:
    return a
  else:
    return b

a = int(input("Enter First Number"))
b = int(input("Enter Second Number"))
print("Max Number is:",maxnumber(a,b))

Enter First Number6
Enter Second Number3
Max Number is: 6


In [51]:
#Python Program to Find the Factorial of a Number
def factorial(a):
  if (a == 1 & a == 0):
    return 1
  else:
    return a * factorial (a - 1)

a = int(input("Enter the Number"))
print("Factorial is:",factorial(a))


Enter the Number5
Factorial is: 120


In [52]:
#Python Program for Simple Interest
def SimpleInterest(a,b,c):
  interest = (a*b*c)/100
  return interest

a = int(input("Enter Principle Amount: "))
b = int(input("Enter Time Period: "))
c = int(input("Enter rate of Interest: "))
print("Simple Interest is:",SimpleInterest(a,b,c))

Enter Principle Amount: 5000
Enter Time Period: 4
Enter rate of Interest: 3
Simple Interest is: 600.0


In [53]:
#Python Program for Compound Interest
def CompoundInterest(p,r,t):
  a = p * (pow((1 + r/100),t))
  CompoundInterest = a - p
  return CompoundInterest

p = int(input("Enter Principle Amount: "))
t = int(input("Enter Time Period: "))
r = int(input("Enter rate of Interest: "))
print("Compound Interest is:",CompoundInterest(p,r,t))

Enter Principle Amount: 3000
Enter Time Period: 2
Enter rate of Interest: 3
Compound Interest is: 182.69999999999982


In [54]:
#Python Program to Find Area of a Circle
def area(rd):
  Pi = 3.14
  return Pi * (rd * rd)

rd = float(input("Enter the radius: "))
print("Area is :",area(rd))


Enter the radius: 3.4
Area is : 36.2984


In [55]:
#Program to print ASCII Value of a character
c = 'A'
print("The ASCII value of '" + c + "' is", ord(c))

The ASCII value of 'A' is 65


In [56]:
#Find sum of square of first n natural numbers
def squaresum(n):
	sm = 0
	for i in range(1, n+1):
		sm = sm + (i * i)
	return sm

n = int(input("Enter the Number: "))
print(squaresum(n))

Enter the Number: 4
30


In [57]:
def Cubesum(n):
	cm = 0
	for i in range(1, n+1):
		cm = cm + (i * i * i)
	return cm

n = int(input("Enter the Number: "))
print(Cubesum(n))

Enter the Number: 6
441


In [58]:
def Fibonacci(n):
    if n<= 0:
        print("Incorrect input")
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return Fibonacci(n-1)+Fibonacci(n-2)


n = int(input("Enter the Number: "))
print(Fibonacci(n))

Enter the Number: 3
1


**Array Problems**

In [59]:
#Find sum of elements in given array
def sum_of_array(arr):
  sum = 0
  for i in arr:
    sum = sum + i;
  return(sum)

arr = [1,2,3,4,5]
t_sum = sum_of_array(arr)
print("Sum of Array: ",t_sum)


Sum of Array:  15


In [60]:
#Max Number from Array
def max_array(arr):
  ans = max(arr)
  return ans

arr = [1,2,3,4,5]
Max = max_array(arr)
print("Max from Array: ",Max)

Max from Array:  5


In [61]:
#Find remainder of array multiplication divided by n
arr = [100, 10, 5, 25, 35, 14];lens = len(arr);n = 11
mul = 1
for i in range(lens):
    mul = (mul * (arr[i] % n)) % n
print(mul % n)

9


In [62]:
# Check if given array is Monotonic
def isMonotonic(A):
    x, y = [], []
    x.extend(A)
    y.extend(A)
    x.sort()
    y.sort(reverse=True)
    if(x == A or y == A):
        return True
    return False


# Driver program
A = [6, 5, 4, 4]

# Print required result
print(isMonotonic(A))

True


**List Problems**

In [63]:
def swapList(newList):

    newList[0], newList[-1] = newList[-1], newList[0]

    return newList

newList = [12, 35, 9, 56, 24]
print(swapList(newList))

[24, 35, 9, 56, 12]


In [64]:
def swapPositions(list, pos1, pos2):

    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list

List = [23, 65, 19, 90]
pos1, pos2  = 0, 3

print(swapPositions(List, pos1, pos2))

[90, 65, 19, 23]


In [67]:
# Python program to find largest number in a list
list1 = [10, 20, 4, 45, 99]
list1.sort()

print("Largest element is:", list1[-1])

Largest element is: 99


In [68]:
# Python program to find N largest element from given list of integers
l = [1000, 298, 3579, 100, 200, -45, 900]
n = 4
l.sort()
print(l[-n:])

[298, 900, 1000, 3579]


In [69]:
# Python program to print odd Numbers in given range

start = int(input("Enter the start of range:"))
end = int(input("Enter the end of range:"))

for num in range(start, end + 1):
    if num % 2 != 0:
        print(num)

Enter the start of range:5
Enter the end of range:10
5
7
9


In [70]:
# Python program to print negative Numbers in a List
list1 = [11, -21, 0, 45, 66, -93]
for num in list1:
    if num < 0:
       print(num, end=" ")

-21 -93 

In [71]:
# Python program to remove multiple
list1 = [11, 5, 17, 18, 23, 50]
unwanted_num = {11, 5}

list1 = [ele for ele in list1 if ele not in unwanted_num]
print("New list after removing unwanted numbers: ", list1)

New list after removing unwanted numbers:  [17, 18, 23, 50]


In [ ]:
# Demonstrate Remove empty List
# from List using filter() Method
test_list = [5, 6, [], 3, [], [], 9]
res = list(filter(None, test_list))
print("List after empty list removal : " + str(res))

In [74]:
# Python code to clone or copy a list
def Cloning(li1):
    li_copy =[]
    li_copy = li1.copy()
    return li_copy
li1 = [4, 8, 2, 10, 15, 18]
li2 = Cloning(li1)
print("Original List:", li1)
print("After Cloning:", li2)

Original List: [4, 8, 2, 10, 15, 18]
After Cloning: [4, 8, 2, 10, 15, 18]


In [73]:
# Python program to print duplicates from
lis = [1, 2, 1, 2, 3, 4, 5, 1, 1, 2, 5, 6, 7, 8, 9, 9]

uniqueList = []
duplicateList = []

for i in lis:
    if i not in uniqueList:
        uniqueList.append(i)
    elif i not in duplicateList:
        duplicateList.append(i)

print(duplicateList)

[1, 2, 5, 9]


**Matrix Questions**

In [75]:
import numpy as np

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = np.array(X) + np.array(Y)

print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [76]:
# Matrix Product
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
res = 1
for i in test_list:
    for j in i:
        res *= j
print("The total element product in lists is : " + str(res))

The total element product in lists is : 1622880


In [77]:
#Matrix Addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print(np.add(A, B))

[[ 5  7]
 [ 9 11]]


In [78]:
#Transpose of Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [79]:
#Vertical Concatenation in Matrix
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
max_len = max(len(sublist) for sublist in test_list)
padded_list = [sublist + [''] * (max_len - len(sublist)) for sublist in test_list]
arr = np.array(padded_list)
arr_t = arr.T
res = [''.join(row) for row in arr_t]
print("List after column concatenation: " + str(res))

List after column concatenation: ['GfgisBest', 'goodfor']


**Strings Question**

In [80]:
#Program to Check if a String is Palindrome or Not
def isPalindrome(s):
    return s == s[::-1]
s = "aabbbaa"
ans = isPalindrome(s)

if ans:
    print("Yes")
else:
    print("No")

Yes


In [81]:
#Check if a Substring is Present in a Given String
MyString1 = "My name is hassan masood"

if "name" in MyString1:
    print("Yes! it is present in the string")
else:
    print("No! it is not present")

Yes! it is present in the string


In [82]:
#Convert Snake case to Pascal case
string = 'hassan_masood'
words = string.split('_')
capitalized_words = [word.title() for word in words]
result = ''.join(capitalized_words)

print(result)

HassanMasood


In [83]:
from collections import Counter
test_str = "hassan"
res = Counter(test_str)
res = min(res, key = res.get)
print ("The minimum of all characters in hassan is : " + str(res))

The minimum of all characters in hassan is : h


In [84]:
import string
def check_string(s):
    for c in s:
        if c in string.punctuation:
            print("String is not accepted")
            return
    print("String is accepted")

check_string("Hassan@masood")
check_string("Hassan Masood")

String is not accepted
String is accepted


In [85]:
# to split and join given string
s = 'Hassan Masood'
print(s.split(" "))
print("-".join(s.split()))

['Hassan', 'Masood']
Hassan-Masood


In [86]:
input_string = "Hassan Masood"
s1 = "Hassan"
s2 = "ababab"
input_string = input_string.replace(s1, s2)
print(input_string)

ababab Masood


**Tuple**

In [87]:
# sample Tuples
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Geek1", "Raju", "Geek2", "Nikhil", "Geek3", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
print("Size of Tuple1: " + str(Tuple1.__sizeof__()) + "bytes")
print("Size of Tuple2: " + str(Tuple2.__sizeof__()) + "bytes")
print("Size of Tuple3: " + str(Tuple3.__sizeof__()) + "bytes")

Size of Tuple1: 72bytes
Size of Tuple2: 72bytes
Size of Tuple3: 56bytes


In [88]:
# Maximum and Minimum K elements in Tuple
test_tup = (5, 20, 3, 7, 6, 8)
K = 2
test_tup = list(test_tup)
temp = sorted(test_tup)
res = tuple(temp[:K] + temp[-K:])
print("The extracted values : " + str(res))

The extracted values : (3, 5, 8, 20)


In [89]:
# Remove Tuples of Length K
test_list = [(4, 5), (4, ), (8, 6, 7), (1, ), (3, 4, 6, 7)]
K = 1
res = [ele for ele in test_list if len(ele) != K]
print("Filtered list : " + str(res))

Filtered list : [(4, 5), (8, 6, 7), (3, 4, 6, 7)]


In [90]:
#sort tuple
from operator import itemgetter
def sort_tuples(tuples):
    return sorted(tuples, key=itemgetter(1))
tuples = [('fast', 24), ('hassan', 8), ('masood', 30)]
print(sort_tuples(tuples))

[('hassan', 8), ('fast', 24), ('masood', 30)]


**Dictionary Questions**

In [92]:
#Append Dictionary Keys and Values ( In order ) in dictionary
test_dict = {"Gfg" : 1, "is" :  3, "Best" : 2}
res = list(test_dict.keys()) + list(test_dict.values())
print("The ordered keys and values : " + str(res))

The ordered keys and values : ['Gfg', 'is', 'Best', 1, 3, 2]


In [93]:
myDict = {'ravi': 10, 'rajnish': 9,
        'sanjeev': 15, 'yash': 2, 'suraj': 32}

myKeys = list(myDict.keys())
myKeys.sort()
sorted_dict = {i: myDict[i] for i in myKeys}

print(sorted_dict)

{'rajnish': 9, 'ravi': 10, 'sanjeev': 15, 'suraj': 32, 'yash': 2}


In [94]:
# Function to print sum
def returnSum(dict):
    sum = 0
    for i in dict.values():
        sum = sum + i
    return sum
dict = {'a': 100, 'b': 200, 'c': 300}
print("Sum :", returnSum(dict))

Sum : 600


In [95]:
# Python code to convert into dictionary
def Convert(tup, di):
    for a, b in tup:
        di.setdefault(a, []).append(b)
    return di
tups = [("akash", 10), ("gaurav", 12), ("anand", 14),
        ("suraj", 20), ("akhil", 25), ("ashish", 30)]
dictionary = {}
print(Convert(tups, dictionary))

{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
